<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HeuristicLab.Core" Version="3.3.*" />
    <PackageReference Include="HeuristicLab.Algorithms.GeneticProgramming" Version="3.3.*" />
    <PackageReference Include="HeuristicLab.Problems.DataAnalysis.Symbolic" Version="3.3.*" />
    <PackageReference Include="HeuristicLab.Encodings.SymbolicExpressionTreeEncoding" Version="3.3.*" />
    <PackageReference Include="HeuristicLab.Operators.GeneticProgramming" Version="3.3.*" />
    <PackageReference Include="HeuristicLab.Persistence" Version="3.3.*" />
    <PackageReference Include="HeuristicLab.Items" Version="3.3.*" />
  </ItemGroup>

</Project>
